logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  error:
    whitelabel:
      enabled: false
  port: 8090
spring:
  datasource:
    username: easjnssveclwig
    password: 9057c119e1f158bed545bcc14c8190c65db9442c6ad20a3e56310a48a68378eb
    url: jdbc:postgresql://ec2-54-173-77-184.compute-1.amazonaws.com/dekjrnovmvu8il
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
